"""change all to cascade

Revision ID: 03e839257e15
Revises: 65b35ef644a0
Create Date: 2020-05-22 00:52:35.655025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e839257e15'
down_revision = '65b35ef644a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blacklist_block_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_blacklist_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_blacklist_block_id_users'), 'users', ['block_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_blacklist_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments_likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_likes_comment_id_comments', type_='foreignkey')
        batch_op.drop_constraint('fk_comments_likes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_likes_comment_id_comments'), 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comments_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_followers_followed_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_followers_follower_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_followers_followed_id_users'), 'users', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_followers_follower_id_users'), 'users', ['follower_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('microcons_collects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_microcons_collects_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_microcons_collects_microcon_id_microcons', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_collects_microcon_id_microcons'), 'microcons', ['microcon_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_collects_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('microcons_cons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_microcons_cons_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_microcons_cons_microcon_id_microcons', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_cons_microcon_id_microcons'), 'microcons', ['microcon_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_cons_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('microcons_likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_microcons_likes_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_microcons_likes_microcon_id_microcons', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_likes_microcon_id_microcons'), 'microcons', ['microcon_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('microcons_micropubs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_microcons_micropubs_microcon_id_microcons', type_='foreignkey')
        batch_op.drop_constraint('fk_microcons_micropubs_micropub_id_micropubs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_micropubs_micropub_id_micropubs'), 'micropubs', ['micropub_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_micropubs_microcon_id_microcons'), 'microcons', ['microcon_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('micropubs_collects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_micropubs_collects_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_micropubs_collects_micropub_id_micropubs', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_micropubs_collects_micropub_id_micropubs'), 'micropubs', ['micropub_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_micropubs_collects_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('micropubs_likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_micropubs_likes_micropub_id_micropubs', type_='foreignkey')
        batch_op.drop_constraint('fk_micropubs_likes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_micropubs_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_micropubs_likes_micropub_id_micropubs'), 'micropubs', ['micropub_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micropubs_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_micropubs_likes_micropub_id_micropubs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_micropubs_likes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_micropubs_likes_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_micropubs_likes_micropub_id_micropubs', 'micropubs', ['micropub_id'], ['id'])

    with op.batch_alter_table('micropubs_collects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_micropubs_collects_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_micropubs_collects_micropub_id_micropubs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_micropubs_collects_micropub_id_micropubs', 'micropubs', ['micropub_id'], ['id'])
        batch_op.create_foreign_key('fk_micropubs_collects_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('microcons_micropubs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_microcons_micropubs_microcon_id_microcons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_microcons_micropubs_micropub_id_micropubs'), type_='foreignkey')
        batch_op.create_foreign_key('fk_microcons_micropubs_micropub_id_micropubs', 'micropubs', ['micropub_id'], ['id'])
        batch_op.create_foreign_key('fk_microcons_micropubs_microcon_id_microcons', 'microcons', ['microcon_id'], ['id'])

    with op.batch_alter_table('microcons_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_microcons_likes_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_microcons_likes_microcon_id_microcons'), type_='foreignkey')
        batch_op.create_foreign_key('fk_microcons_likes_microcon_id_microcons', 'microcons', ['microcon_id'], ['id'])
        batch_op.create_foreign_key('fk_microcons_likes_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('microcons_cons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_microcons_cons_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_microcons_cons_microcon_id_microcons'), type_='foreignkey')
        batch_op.create_foreign_key('fk_microcons_cons_microcon_id_microcons', 'microcons', ['microcon_id'], ['id'])
        batch_op.create_foreign_key('fk_microcons_cons_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('microcons_collects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_microcons_collects_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_microcons_collects_microcon_id_microcons'), type_='foreignkey')
        batch_op.create_foreign_key('fk_microcons_collects_microcon_id_microcons', 'microcons', ['microcon_id'], ['id'])
        batch_op.create_foreign_key('fk_microcons_collects_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_followers_follower_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_followers_followed_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_followers_follower_id_users', 'users', ['follower_id'], ['id'])
        batch_op.create_foreign_key('fk_followers_followed_id_users', 'users', ['followed_id'], ['id'])

    with op.batch_alter_table('comments_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_likes_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comments_likes_comment_id_comments'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_likes_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_comments_likes_comment_id_comments', 'comments', ['comment_id'], ['id'])

    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_blacklist_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_blacklist_block_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_blacklist_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_blacklist_block_id_users', 'users', ['block_id'], ['id'])

    # ### end Alembic commands ###
