"""correct spelling

Revision ID: 65b35ef644a0
Revises: 56ee3b822c31
Create Date: 2020-05-22 00:22:48.661357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b35ef644a0'
down_revision = '56ee3b822c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microcons_pors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_microcons_pors_microcon_id_microcons', type_='foreignkey')
        batch_op.drop_constraint('fk_microcons_pors_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_pors_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_microcons_pors_microcon_id_microcons'), 'microcons', ['microcon_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microcons_pors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_microcons_pors_microcon_id_microcons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_microcons_pors_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_microcons_pors_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_microcons_pors_microcon_id_microcons', 'microcons', ['microcon_id'], ['id'])

    # ### end Alembic commands ###
