"""add sponsors done

Revision ID: 98719838fd82
Revises: a15f34263f6c
Create Date: 2020-05-19 16:09:11.558838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98719838fd82'
down_revision = 'a15f34263f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ddls_deadline'), ['deadline'], unique=False)

    with op.batch_alter_table('microknos_cites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microknos_cites', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('ddls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ddls_deadline'))
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
