"""add microcons status

Revision ID: ca7037a8accb
Revises: bcc5d784316e
Create Date: 2020-05-13 00:20:14.499973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7037a8accb'
down_revision = 'bcc5d784316e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microcons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microcons', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
